### ISSUE TITLE
Rename the key

### ISSUE THREAD

**Issue by wallysonn** [mioxs/pinia-plugin-store#2]
How do I rename the key without having to rename the storage? Example:

` stores: [
    {
      name: 'user',
      storage: sessionStorage,
      key: 'my-renamed-key',
    },
    {
      name: 'count',
      storage: localStorage,
    },
  ]`

**Comment by mioxs** [comment]
It is recommended to use
```ts
import { createPinia, setMapStoreSuffix } from 'pinia'

setMapStoreSuffix('') // completely remove the suffix
export const pinia = createPinia()

declare module 'pinia' {
  export interface MapStoresCustomization {
    // set it to the same value as above
    suffix: ''
  }
}
```
