### ISSUE TITLE
No load on local storage

### ISSUE THREAD

**Issue by kydner** [mioxs/pinia-plugin-store#3]
`function encrypt(value: string): string {
  return Encrypt(value)
}

function decrypt(value: string): string {
  if (value) {
    Decrypt(value)
  }
  return ''
}
const piniaPlugin = storePlugin({
  stores: ['auth', 'student],
  encrypt,
  decrypt,
})`

i has set like this, but when i reload browser pinia always reset by default, not load by localStorage

**Comment by mioxs** [comment]
function decrypt(value: string): string {

   return Decrypt(value)


}
```

**Comment by mivui** [comment]
fix v2.1.31
